# from a prcomp object, get the importance of a principal component in terms of the amount of variation it explains
# prcomp is pca object generated by prcomp
# pc the number of the principal component
# percentage (logical) is whether to report variance explained as a percentage
# rounding_digits is number of decimal places to round to
pca_importance <- function(prcomp, pc, percentage = T, rounding_digits = 1){
  imp <- summary(prcomp)$importance[2, pc] 
  if(percentage){
    imp <- imp * 100
  }
   imp %>% round(rounding_digits)
}
